try {
  console.log('inside try{} till myVar');
  myVar;
  console.log('inside try{} after myVar');
} catch {
  console.log('ERROR!!!');
}

console.log('After try...catch!');
